/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Components;
import Components.ActivitiesComp.ActivitiesPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author Atahan
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();
        //my init components
        sideMenu1 = new Components.SideMenu(this);
        appPanel.add(sideMenu1, java.awt.BorderLayout.WEST);
        pack();
        setLocationRelativeTo(null);
        
        notificationBtn.setColorClicked(new Color(177, 177, 177));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationsPanel = new Components.NotifComp.NotificationsPanel();
        appPanel = new javax.swing.JPanel();
        featuresPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        notificationBtn = new Components.Button();
        infoText = new javax.swing.JLabel();
        showPane = new javax.swing.JPanel();
        activitiesPanel = new Components.ActivitiesComp.ActivitiesPanel();
        settingsPanel = new Components.SettingsComp.SettingsPanel();
        createActPanel = new Components.ActivitiesComp.CreateActivityPanel();
        profilePanel = new Components.ProfileComp.ProfilePanel();
        messagesPanel = new Components.MessagesComp.MessagesPanel();
        schedulerPanel = new Components.SchedulerComp.SchedulerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppFrame");
        setMaximumSize(new java.awt.Dimension(1920, 1024));
        setMinimumSize(new java.awt.Dimension(1480, 800));
        setPreferredSize(new java.awt.Dimension(1620, 1024));
        setSize(new java.awt.Dimension(1640, 1024));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));
        getContentPane().add(notificationsPanel);

        appPanel.setBackground(new java.awt.Color(235, 240, 255));
        appPanel.setLayout(new java.awt.BorderLayout());

        featuresPanel.setBackground(new java.awt.Color(235, 240, 255));
        featuresPanel.setLayout(new java.awt.BorderLayout());

        infoPanel.setBackground(new java.awt.Color(253, 254, 254));
        infoPanel.setPreferredSize(new java.awt.Dimension(1146, 80));

        notificationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bell.png"))); // NOI18N
        notificationBtn.setRoundness(1000);
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        infoText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        infoText.setText("Current Page Name");
        infoText.setMaximumSize(new java.awt.Dimension(208, 32));
        infoText.setMinimumSize(new java.awt.Dimension(208, 32));
        infoText.setPreferredSize(new java.awt.Dimension(208, 32));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(infoText, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(infoText, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );

        featuresPanel.add(infoPanel, java.awt.BorderLayout.PAGE_START);

        showPane.setBackground(new java.awt.Color(235, 240, 255));
        showPane.setLayout(new java.awt.CardLayout());
        showPane.add(activitiesPanel, "card8");

        settingsPanel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );

        showPane.add(settingsPanel, "card7");

        createActPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout createActPanelLayout = new javax.swing.GroupLayout(createActPanel);
        createActPanel.setLayout(createActPanelLayout);
        createActPanelLayout.setHorizontalGroup(
            createActPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        createActPanelLayout.setVerticalGroup(
            createActPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );

        showPane.add(createActPanel, "card6");
        showPane.add(profilePanel, "card8");
        showPane.add(messagesPanel, "card8");

        schedulerPanel.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout schedulerPanelLayout = new javax.swing.GroupLayout(schedulerPanel);
        schedulerPanel.setLayout(schedulerPanelLayout);
        schedulerPanelLayout.setHorizontalGroup(
            schedulerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        schedulerPanelLayout.setVerticalGroup(
            schedulerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );

        showPane.add(schedulerPanel, "card4");

        featuresPanel.add(showPane, java.awt.BorderLayout.CENTER);

        appPanel.add(featuresPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(appPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        notificationsPanel.openNotifications();
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
    }//GEN-LAST:event_formMousePressed
   
    public void switchPanels(JPanel selectedPanel){
        for (Component component : showPane.getComponents()) {
            component.setVisible(false);
        }
        selectedPanel.setVisible(true);
    }
    
    public JPanel getShowPanel(){
        return showPane;
    }

    public ActivitiesPanel getActivitiesPanel() {
        return activitiesPanel;
    }

    public JPanel getMessagesPanel() {
        return messagesPanel;
    }
    
    public JPanel getSchedulerPanel() {
        return schedulerPanel;
    }
    
    public JPanel getProfilePanel(){
        return profilePanel;
    }
    
    public JPanel getCreateActivityPanel(){
        return createActPanel;
    }
    
    public JPanel getSettingsPanel(){
        return settingsPanel;
    }
    
    public JLabel getInfoText(){
        return infoText;
    }
    
    public void setInfoText(String str){
        infoText.setText(str);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ActivitiesComp.ActivitiesPanel activitiesPanel;
    private javax.swing.JPanel appPanel;
    private Components.ActivitiesComp.CreateActivityPanel createActPanel;
    private javax.swing.JPanel featuresPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel infoText;
    private Components.MessagesComp.MessagesPanel messagesPanel;
    private Components.Button notificationBtn;
    private Components.NotifComp.NotificationsPanel notificationsPanel;
    private Components.ProfileComp.ProfilePanel profilePanel;
    private Components.SchedulerComp.SchedulerPanel schedulerPanel;
    private Components.SettingsComp.SettingsPanel settingsPanel;
    private javax.swing.JPanel showPane;
    // End of variables declaration//GEN-END:variables
    private JPanel sideMenu1;
}
