/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Components;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;
/**
 *
 * @author Atahan
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();
        //my init components
        sideMenu1 = new Components.SideMenu(this);
        getContentPane().add(sideMenu1, java.awt.BorderLayout.WEST);
        pack();
        setLocationRelativeTo(null);
        
        NotificationBtn.setColorClicked(new Color(177, 177, 177));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        featuresPanel = new javax.swing.JPanel();
        InformationPanel = new javax.swing.JPanel();
        NotificationBtn = new Components.Button();
        InfoText = new javax.swing.JLabel();
        showPane = new javax.swing.JPanel();
        settingsPanel1 = new Components.SettingsPanel();
        createActivityPanel1 = new Components.CreateActivityPanel();
        profilePanel1 = new Components.ProfilePanel();
        activitiesPanel = new Components.ActivitiesPanel();
        messagesPanel1 = new Components.MessagesPanel();
        schedulerPanel1 = new Components.SchedulerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppFrame");
        setMaximumSize(new java.awt.Dimension(1920, 1024));
        setMinimumSize(new java.awt.Dimension(1024, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setSize(new java.awt.Dimension(1440, 1024));

        featuresPanel.setBackground(new java.awt.Color(235, 240, 255));
        featuresPanel.setLayout(new java.awt.BorderLayout());

        InformationPanel.setBackground(new java.awt.Color(253, 254, 254));
        InformationPanel.setPreferredSize(new java.awt.Dimension(1146, 80));

        NotificationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bell.png"))); // NOI18N
        NotificationBtn.setRoundness(1000);
        NotificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationBtnActionPerformed(evt);
            }
        });

        InfoText.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        InfoText.setText("Current Page Name");
        InfoText.setMaximumSize(new java.awt.Dimension(208, 32));
        InfoText.setMinimumSize(new java.awt.Dimension(208, 32));
        InfoText.setPreferredSize(new java.awt.Dimension(208, 32));

        javax.swing.GroupLayout InformationPanelLayout = new javax.swing.GroupLayout(InformationPanel);
        InformationPanel.setLayout(InformationPanelLayout);
        InformationPanelLayout.setHorizontalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(InfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                .addComponent(NotificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        InformationPanelLayout.setVerticalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformationPanelLayout.createSequentialGroup()
                        .addComponent(NotificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InformationPanelLayout.createSequentialGroup()
                        .addComponent(InfoText, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );

        featuresPanel.add(InformationPanel, java.awt.BorderLayout.PAGE_START);

        showPane.setLayout(new java.awt.CardLayout());

        settingsPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout settingsPanel1Layout = new javax.swing.GroupLayout(settingsPanel1);
        settingsPanel1.setLayout(settingsPanel1Layout);
        settingsPanel1Layout.setHorizontalGroup(
            settingsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        settingsPanel1Layout.setVerticalGroup(
            settingsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(settingsPanel1, "card7");

        createActivityPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout createActivityPanel1Layout = new javax.swing.GroupLayout(createActivityPanel1);
        createActivityPanel1.setLayout(createActivityPanel1Layout);
        createActivityPanel1Layout.setHorizontalGroup(
            createActivityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        createActivityPanel1Layout.setVerticalGroup(
            createActivityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(createActivityPanel1, "card6");

        profilePanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout profilePanel1Layout = new javax.swing.GroupLayout(profilePanel1);
        profilePanel1.setLayout(profilePanel1Layout);
        profilePanel1Layout.setHorizontalGroup(
            profilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        profilePanel1Layout.setVerticalGroup(
            profilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(profilePanel1, "card5");

        javax.swing.GroupLayout activitiesPanelLayout = new javax.swing.GroupLayout(activitiesPanel);
        activitiesPanel.setLayout(activitiesPanelLayout);
        activitiesPanelLayout.setHorizontalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        activitiesPanelLayout.setVerticalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(activitiesPanel, "card3");

        messagesPanel1.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout messagesPanel1Layout = new javax.swing.GroupLayout(messagesPanel1);
        messagesPanel1.setLayout(messagesPanel1Layout);
        messagesPanel1Layout.setHorizontalGroup(
            messagesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        messagesPanel1Layout.setVerticalGroup(
            messagesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(messagesPanel1, "card4");

        schedulerPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout schedulerPanel1Layout = new javax.swing.GroupLayout(schedulerPanel1);
        schedulerPanel1.setLayout(schedulerPanel1Layout);
        schedulerPanel1Layout.setHorizontalGroup(
            schedulerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
        );
        schedulerPanel1Layout.setVerticalGroup(
            schedulerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1821, Short.MAX_VALUE)
        );

        showPane.add(schedulerPanel1, "card4");

        featuresPanel.add(showPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(featuresPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationBtnActionPerformed
   
    public void switchPanels(JPanel selectedPanel){
        for (Component component : showPane.getComponents()) {
            component.setVisible(false);
        }
        selectedPanel.setVisible(true);
    }
    
    public JPanel getShowPanel(){
        return showPane;
    }

    public JPanel getActivitiesPanel() {
        return activitiesPanel;
    }

    public JPanel getMessagesPanel() {
        return messagesPanel1;
    }
    
    public JPanel getSchedulerPanel() {
        return schedulerPanel1;
    }
    
    public JPanel getProfilePanel(){
        return profilePanel1;
    }
    
    public JPanel getCreateActivityPanel(){
        return createActivityPanel1;
    }
    
    public JPanel getSettingsPanel(){
        return settingsPanel1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoText;
    private javax.swing.JPanel InformationPanel;
    private Components.Button NotificationBtn;
    private Components.ActivitiesPanel activitiesPanel;
    private Components.CreateActivityPanel createActivityPanel1;
    private javax.swing.JPanel featuresPanel;
    private Components.MessagesPanel messagesPanel1;
    private Components.ProfilePanel profilePanel1;
    private Components.SchedulerPanel schedulerPanel1;
    private Components.SettingsPanel settingsPanel1;
    private javax.swing.JPanel showPane;
    // End of variables declaration//GEN-END:variables
    private JPanel sideMenu1;
}
