/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components.ProfileComp;

import Main.User;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;


/**
 *
 * @author denizcaglar
 */
public class ProfileItem extends javax.swing.JPanel {
    
    private User user;
    private String username;
  
    public ProfileItem(User user) {
        initComponents();
        setBackground(Color.WHITE);
        this.user = user;
        updateUIComponents();
    }
    
    private void updateUIComponents() {
        userNameLabel.setText(user.getUsername());
        nameLabel.setText(user.getDisplayName());
        
        BufferedImage profilePic = user.getProfilePic();
        if (profilePic != null) 
        {
            profileImage.setIcon(new ImageIcon(profilePic));
        } 
        else 
        {
            profileImage.setIcon(new ImageIcon(getClass().getResource("/icons/user.png")));
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileImage = new Components.ImageAvatar();
        userNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 200));

        userNameLabel.setText("jLabel1");

        nameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(userNameLabel)
                .addGap(64, 64, 64)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel)
                            .addComponent(nameLabel))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private Components.ImageAvatar profileImage;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
