package Components.MessagesComp;

import Components.AppFrame;
import Components.RefreshablePanel;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import Components.ScrollBarUI;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import Main.User;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Atahan
 */
public class MessagesPanel extends javax.swing.JPanel implements RefreshablePanel{

    private List<User> friends;
    private final AppFrame a;
    
    public MessagesPanel (AppFrame a) {
        initComponents();
        this.a = a;
        
        Chats.setLayout(new GridBagLayout());
        Chats.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        ChatsScrollPane.setBorder(null);
        ChatsScrollPane.setViewportView(Chats);
        ChatsScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        ChatsScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        ChatsScrollPane.getVerticalScrollBar().setUI(new ScrollBarUI());
        ChatsScrollPane.getViewport().setBackground(new Color(255, 255, 255));
        
        this.friends = fetchFriendsFromServer();
        displayAllChats();
        
    }
    
    public void refresh(){
        //TODO
    }
    
    private List<User> fetchFriendsFromServer() {
        
        List<User> friends = new ArrayList<>();
        friends.add(new User("Friend1", "friend1@example.com", "password1"));
        friends.add(new User("Friend2", "friend2@example.com", "password2"));
        friends.add(new User("Friend3", "friend3@example.com", "password3"));
        friends.add(new User("Friend4", "friend4@example.com", "password4"));
        friends.add(new User("Friend5", "friend5@example.com", "password5"));

        return friends;
    }
    
    private void displayAllChats() {
        
        List<Chat> chatList = new ArrayList<>();

        for (User friend : friends) {
            Date lastMessageTime = getLastMessageTimeForUser(friend);
            Chat chat = new Chat(friend, "e", "e", this, lastMessageTime);
            chatList.add(chat);
        }

        // Sort chatList based on the last sent message time
        Collections.sort(chatList);

        // Clear existing components in Chats
        Chats.removeAll();

        // Add sorted chats back to Chats panel
        for (Chat chat : chatList) {
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = GridBagConstraints.RELATIVE;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            gbc.insets = new Insets(5, 5, 5, 5);

            Chats.add(chat, gbc);
        }

        Chats.revalidate();
    }
    
    public void updateDisplay (MessagePanel m) {
        Chats.removeAll();
        if (m != null) {
            m.setBorder(BorderFactory.createLineBorder(null));
            m.setVisible(true);
            Chats.add(m);
            ChatsScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        } else {
            displayAllChats();
            ChatsScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        }
        
        Chats.revalidate();  
    }
    
    public AppFrame getAppFrame () {
        return this.a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChatsScrollPane = new javax.swing.JScrollPane();
        Chats = new Components.RoundedPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setMaximumSize(new java.awt.Dimension(1150, 800));
        setMinimumSize(new java.awt.Dimension(1150, 800));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1150, 800));

        ChatsScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        ChatsScrollPane.setBorder(null);

        Chats.setBackground(new java.awt.Color(255, 255, 255));
        Chats.setMaximumSize(new java.awt.Dimension(1050, 700));
        Chats.setMinimumSize(new java.awt.Dimension(1050, 700));

        javax.swing.GroupLayout ChatsLayout = new javax.swing.GroupLayout(Chats);
        Chats.setLayout(ChatsLayout);
        ChatsLayout.setHorizontalGroup(
            ChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ChatsLayout.setVerticalGroup(
            ChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ChatsScrollPane.setViewportView(Chats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(ChatsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ChatsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.RoundedPanel Chats;
    private javax.swing.JScrollPane ChatsScrollPane;
    // End of variables declaration//GEN-END:variables

    private Date getLastMessageTimeForUser(User friend) {
        return new Date();
    }
}
