/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components.NotifComp;

import Components.Button;
import Main.FriendRequest;
import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author Atahan
 */
public class FriendRequestItem extends javax.swing.JPanel {
    FriendRequest friendRequest;
    NotificationsPanel notificationsPanel;
    boolean over;
    /**
     * Creates new form activityItem
     */
    public FriendRequestItem() {
        initComponents();
        roundedPanel.setBackground(new Color(60, 60, 60, 0));  
        over = false;
        acceptButton.setBgColor(Button.RED);
        acceptButton.setColorClicked(new Color(155, 2, 17));
        acceptButton.setTextColor(Color.WHITE);
        denyButton.setBgColor(new Color(214, 214, 214));
        denyButton.setColorClicked(new Color(155, 155, 155));
        denyButton.setTextColor(Color.WHITE);
    }
    
    public FriendRequestItem(FriendRequest friendRequest, NotificationsPanel notificationsPanel) {
        initComponents();
        roundedPanel.setBackground(new Color(60, 60, 60, 0));
        over = false;
        acceptButton.setBgColor(Button.RED);
        acceptButton.setColorClicked(new Color(155, 2, 17));
        acceptButton.setTextColor(Color.WHITE);
        denyButton.setBgColor(new Color(204, 204, 204));
        denyButton.setColorClicked(new Color(155, 155, 155));
        denyButton.setTextColor(Color.WHITE);
        
        this.friendRequest = friendRequest;
        this.notificationsPanel = notificationsPanel;
        
        this.senderName.setText(friendRequest.getSender().getDisplayName());
    }

    
    public void setSender (String str){
        this.senderName.setText(str);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel = new Components.RoundedPanel();
        profilePic = new Components.ImageAvatar();
        acceptButton = new Components.Button();
        denyButton = new Components.Button();
        senderName = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2000, 2000));
        setMinimumSize(new java.awt.Dimension(420, 60));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(420, 60));
        setLayout(new java.awt.BorderLayout());

        roundedPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel.setMaximumSize(new java.awt.Dimension(420, 60));
        roundedPanel.setMinimumSize(new java.awt.Dimension(420, 60));
        roundedPanel.setPreferredSize(new java.awt.Dimension(420, 60));
        roundedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedPanelMouseExited(evt);
            }
        });

        profilePic.setBackground(new java.awt.Color(102, 102, 102));
        profilePic.setForeground(new java.awt.Color(204, 204, 204));
        profilePic.setBorderSize(2);
        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profilePic.png"))); // NOI18N
        profilePic.setOpaque(true);

        acceptButton.setBackground(new java.awt.Color(255, 51, 51));
        acceptButton.setText("Accept");
        acceptButton.setAlignmentY(0.7F);
        acceptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acceptButton.setMargin(new java.awt.Insets(2, 16, 3, 12));
        acceptButton.setRoundness(15);
        acceptButton.setVerticalTextPosition(SwingConstants.CENTER);
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        denyButton.setBackground(new java.awt.Color(204, 204, 204));
        denyButton.setText("Deny");
        denyButton.setAlignmentY(0.7F);
        denyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyButtonActionPerformed(evt);
            }
        });

        senderName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        senderName.setForeground(new java.awt.Color(51, 51, 51));
        senderName.setText("Sender Name");

        javax.swing.GroupLayout roundedPanelLayout = new javax.swing.GroupLayout(roundedPanel);
        roundedPanel.setLayout(roundedPanelLayout);
        roundedPanelLayout.setHorizontalGroup(
            roundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(denyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        roundedPanelLayout.setVerticalGroup(
            roundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelLayout.createSequentialGroup()
                .addGroup(roundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(roundedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(denyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(roundedPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanelMouseEntered
        roundedPanel.setBackground(new Color(60, 60, 60, 20));
    }//GEN-LAST:event_roundedPanelMouseEntered

    private void roundedPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanelMouseExited
       roundedPanel.setBackground(new Color(60, 60, 60, 0));
    }//GEN-LAST:event_roundedPanelMouseExited

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        friendRequest.acceptRequest();
        notificationsPanel.removeItem(this);
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void denyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyButtonActionPerformed
        friendRequest.denyRequest();
        notificationsPanel.removeItem(this);
    }//GEN-LAST:event_denyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button acceptButton;
    private Components.Button denyButton;
    private Components.ImageAvatar profilePic;
    private Components.RoundedPanel roundedPanel;
    private javax.swing.JLabel senderName;
    // End of variables declaration//GEN-END:variables
}
